### ISSUE TITLE
Implement tests in Github actions

### ISSUE THREAD

**Issue by FlxPeters** [e-breuninger/terraform-provider-ignition#26]
We should have basic tests to validate automated pull requests and new featues. 
there seam to be some tests implemented, but not executed.

**Comment by FlxPeters** [comment]
Also the pre-commit checks are only executed on branches but not on pull requests

**Comment by torvitas** [comment]
The tests are being executed as part of the pre-commit-hooks. Pre-commit-hooks now run on PRs.
